### ISSUE TITLE
Change DNS settings

### ISSUE THREAD

**Issue by danez** [babel/phabricator-to-github#19]
- [ ] Change `phabricator.babeljs.io` to be a `CNAME` to `babel.github.io.`
- [ ] Add `phabricator.babeljs.io` as custom domain for github-pages in https://github.com/babel/phabricator-redirects/settings

@thejameskyle @kittens Can someone of you do this? That would be nice and should not be that hard.

For reference: Currently the domain is pointing to:

```
❯ nslookup phabricator.babeljs.io
Server:     192.168.127.253
Address:    192.168.127.253#53

Non-authoritative answer:
Name:   phabricator.babeljs.io
Address: 104.27.143.153
Name:   phabricator.babeljs.io
Address: 104.27.142.153
```

**Comment by Daniel15** [comment]
I assume this means that the old Phabricator URLs (using the `phabricator.babeljs.io` domain) will magically redirect to the right place?

Is it possible to use 301 redirects (mainly for SEO) rather than the old-school meta redirects that are being used at the moment?

**Comment by danez** [comment]
Currently the redirects are done with html-meta-refresh, this is not super nice but github pages don't allow to send custom headers. For seo the html page that redirects has a canonical url set to the new location so that google should know that the redirect page is not the real location i think.

**Comment by Daniel15** [comment]
>  github pages don't allow to send custom headers

Ahh, I see. Yeah, Github Pages has a bunch of limitations. Personally I'm not a fan of the service for hosting 'real' websites. I guess it's fine as a hack.

If you do want proper 301 redirects, I'm happy to host an Nginx vhost for you. The redirects are trivial to do in an Nginx config. 😛
